### PR TITLE
Alia-24: return Date rather than Long from DateTime PCodec

### PR DESCRIPTION
**Pull request by d-t-w**
Related to #24

### CODE REVIEW

**Comment by mpenet** [comment]
Good catch, thanks!

**Comment by d-t-w** [comment]
Pleasure, Alia is brilliant and we use it extensively.

**Comment by mpenet** [comment]
Glad to hear that :+1:  

It's on clojars as 2.3.5

**Comment by d-t-w** [comment]
Nice! that was quick.

**Comment by mpenet** [comment]
That's how we do it :]

**Pull request merged**
